export enum ActionType {
  GET_PRODUCTS = "GET_PRODUCTS",
  SET_FILTER = "SET_FILTER",
  SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE",
  UPDATE_CART_ITEMS = "ADD_CART_ITEMS",
  SET_USER_INFO = "SET_USER_INFO",
  SET_USER_CARD = "SET_USER_CARD",
  SET_USER_LOCATION = "SET_USER_LOCATION",
  DELETE_ORDER = "DELETE_ORDER",
}
