export enum ActionType {
  GET_PRODUCTS = "GET_PRODUCTS",
  SET_FILTER = "SET_FILTER",
  SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE",
  //ADD_CART_ITEM = "ADD_CART_ITEM",
  UPDATE_CART_ITEMS = "ADD_CART_ITEMS",
}
